server:
  port: 8082

spring:
  application:
    name: gateways

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: resource-module
          uri: lb://resource  # 通过 Nacos 发现，会自动找到 9002
          predicates:
            - Path=/api/**
          filters:
            - TokenRelay

    nacos:
      discovery:
        server-addr: localhost:8848

  security:
    oauth2:
      client:
        registration:
          gateway-client:
            provider: auth-server
            client-id: gateway-client
            client-secret: gateway-secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8082/login/oauth2/code/gateway-client"
            scope: openid,profile,admin
        provider:
          auth-server:
            issuer-uri: http://localhost:9001

logging:
  level:
    com.dp.gateways: DEBUG
    org.springframework.security: DEBUG